<div class="social-share" data-initialized="true">
    <a href="#" class="social-share-icon icon-weibo"></a>
    <a href="#" class="social-share-icon icon-qq"></a>
    <a href="#" class="social-share-icon icon-wechat"></a>
    <a href="#" class="social-share-icon icon-twitter"></a>
    <a href="#" class="social-share-icon icon-google"></a>
</div>
<link rel="stylesheet" href="/lib/sharejs/css/share.min.css">

<!-- share.js -->
<script src="/lib/sharejs/js/social-share.min.js"></script>
